# Generated by Django 3.1.1 on 2020-09-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200920_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
